export const ARTICLE_ADD = 'ADD_ARTICLE';
export const ARTICLE_DELETE = 'DELETE_ARTICLE';
export const ARTICLE_INCR_QUANTITY = 'ARTICLE_INCR_QUANTITY';
export const ARTICLE_DECR_QUANTITY = 'ARTICLE_DECR_QUANTITY';

export const SHOW_BASKET = 'SHOW_BASKET';
export const HIDE_BASKET = 'HIDE_BASKET';