export const ARTICLE_ADD = 'ADD_ARTICLE';
export const ARTICLE_DELETE = 'DELETE_ARTICLE';
export const ARTICLE_INCR_QUANTITY = 'ARTICLE_INCR_QUANTITY';
export const ARTICLE_DECR_QUANTITY = 'ARTICLE_DECR_QUANTITY';
